-- Courses table
create table if not exists courses (
  slug text primary key,
  title text not null default '',
  category text not null default 'offline',
  icon text default '📚',
  color text default '#f77420',
  bg text default '#fff1e8',
  tagline text default '',
  overview text default '',
  duration text default '',
  batch_size text default '',
  mode text default '',
  fee text default '',
  emi text default '',
  features jsonb default '[]',
  includes jsonb default '[]',
  curriculum jsonb default '[]',
  who_for jsonb default '[]',
  testimonial jsonb default '{}',
  created_at timestamptz default now()
);

-- Batches table
create table if not exists batches (
  slug text primary key,
  course_slug text default '',
  category text default 'offline',
  name text not null default '',
  exam text default '',
  batch_code text default '',
  start_date text default '',
  end_date text default '',
  duration text default '',
  schedule text default '',
  mode text default '',
  seats integer default 30,
  filled integer default 0,
  fee text default '',
  original_fee text,
  emi text default '',
  offer text,
  color text default '#f77420',
  bg text default '#e8eeff',
  status text default 'upcoming',
  language text default 'Hinglish',
  batch_type text default '',
  chips jsonb default '[]',
  faculty jsonb default '[]',
  highlights jsonb default '[]',
  syllabus jsonb default '[]',
  description text default '',
  created_at timestamptz default now()
);
