-- Exams table
create table if not exists exams (
  slug text primary key,
  code text not null default '',
  name text not null default '',
  full_name text not null default '',
  tagline text default '',
  icon text default '🏛️',
  color text default '#08BD80',
  bg text default '#E6FAF4',
  seats text default '',
  colleges text default '',
  duration text default '',
  questions integer default 0,
  marks integer default 0,
  negative_mark text default '',
  conducted_by text default '',
  mode text default '',
  overview text default '',
  eligibility jsonb default '[]',
  exam_pattern jsonb default '[]',
  syllabus jsonb default '[]',
  important_dates jsonb default '[]',
  preparation_tips jsonb default '[]',
  faqs jsonb default '[]',
  application_fee jsonb default '[]',
  nlu_list jsonb default '[]',
  latest_updates jsonb default '[]',
  application_process jsonb default '[]',
  created_at timestamptz default now()
);
